[0m12:39:57.666719 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7611bf609060>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7611bfd85a20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7611bfd859c0>]}


============================== 12:39:57.670072 | 01bba188-e9e4-454a-bfee-e3b04cc8fe3f ==============================
[0m12:39:57.670072 [info ] [MainThread]: Running with dbt=1.7.9
[0m12:39:57.670827 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': '/home/vscode/.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt docs generate', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m12:39:57.671453 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-tomisin/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:39:57.672652 [debug] [MainThread]: Resource report: {"command_name": "generate", "command_wall_clock_time": 0.0525448, "process_user_time": 1.915881, "process_kernel_time": 0.283834, "process_mem_max_rss": "86696", "process_in_blocks": "65736", "process_out_blocks": "8", "command_success": false}
[0m12:39:57.673419 [debug] [MainThread]: Command `dbt docs generate` failed at 12:39:57.673254 after 0.05 seconds
[0m12:39:57.673879 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7611bf609060>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7611bfd85ab0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7611bfd859f0>]}
[0m12:39:57.674357 [debug] [MainThread]: Flushing usage events
[0m15:52:54.343669 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f05aca5a380>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f05ad1d59f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f05ad1d5990>]}


============================== 15:52:54.353535 | ba2d2610-8ada-4f8d-a16b-4a63017fac5e ==============================
[0m15:52:54.353535 [info ] [MainThread]: Running with dbt=1.7.9
[0m15:52:54.354505 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '/home/vscode/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'invocation_command': 'dbt run', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:52:54.355092 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-tomisin/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:52:54.356204 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.056928735, "process_user_time": 1.994064, "process_kernel_time": 0.235771, "process_mem_max_rss": "86668", "process_in_blocks": "65424", "process_out_blocks": "8", "command_success": false}
[0m15:52:54.356851 [debug] [MainThread]: Command `dbt run` failed at 15:52:54.356692 after 0.06 seconds
[0m15:52:54.357299 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f05aca5a380>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f05ad1d5a80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f05ad1d5ea0>]}
[0m15:52:54.357780 [debug] [MainThread]: Flushing usage events
<<<<<<< HEAD
[0m09:11:13.559600 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7df7d4e94760>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7df7d35a5c60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7df7d35a5c00>]}


============================== 09:11:13.571489 | d8969481-5aeb-4fd8-b637-4907ed9ab5f7 ==============================
[0m09:11:13.571489 [info ] [MainThread]: Running with dbt=1.8.0
[0m09:11:13.572238 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': '/home/vscode/.dbt', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt test', 'send_anonymous_usage_stats': 'True'}
[0m09:11:13.572776 [error] [MainThread]: Encountered an error:
=======
[0m12:02:36.972104 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff13fc6e230>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff1402dd900>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff1402dd8a0>]}


============================== 12:02:36.977144 | fb56f2f1-3040-4f2b-bf78-2002b5253bed ==============================
[0m12:02:36.977144 [info ] [MainThread]: Running with dbt=1.7.9
[0m12:02:36.977995 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/vscode/.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt seed', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m12:02:36.978641 [error] [MainThread]: Encountered an error:
>>>>>>> 97255912a8adaf0bad2ec0d18d7e9074797e22ca
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-tomisin/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
<<<<<<< HEAD
[0m09:11:13.573836 [debug] [MainThread]: Resource report: {"command_name": "test", "command_wall_clock_time": 0.06268662, "process_user_time": 1.214082, "process_kernel_time": 0.217087, "process_mem_max_rss": "83600", "process_in_blocks": "66440", "process_out_blocks": "8", "command_success": false}
[0m09:11:13.574438 [debug] [MainThread]: Command `dbt test` failed at 09:11:13.574335 after 0.06 seconds
[0m09:11:13.574856 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7df7d4e94760>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7df7d35a5cf0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7df7d35a5c30>]}
[0m09:11:13.575282 [debug] [MainThread]: Flushing usage events
=======
[0m12:02:36.979761 [debug] [MainThread]: Resource report: {"command_name": "seed", "command_wall_clock_time": 0.052244157, "process_user_time": 1.932469, "process_kernel_time": 0.250505, "process_mem_max_rss": "86540", "process_in_blocks": "65424", "process_out_blocks": "8", "command_success": false}
[0m12:02:36.980444 [debug] [MainThread]: Command `dbt seed` failed at 12:02:36.980278 after 0.05 seconds
[0m12:02:36.980920 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff13fc6e230>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff1402dd990>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff1402dddb0>]}
[0m12:02:36.981411 [debug] [MainThread]: Flushing usage events
>>>>>>> 97255912a8adaf0bad2ec0d18d7e9074797e22ca
